#ifndef DEFINES_H
#define DEFINES_H

#define VIRTUAL_SCREEN_WIDTH   1920
#define VIRTUAL_SCREEN_HEIGHT  1080

#define ESCALA_NORMAL_BOTAO   1.3f
#define ESCALA_HOVER_BOTAO    1.65f
#define VELOCIDADE_ANIM_BOTAO 0.08f

#define ESCALA_PEQUENO_BOTAO   0.6f

#endif